#!/bin/bash

github() {
  # retrieve info from git
  branch="$(git rev-parse --abbrev-ref HEAD)"
  url="$(git config --get remote.origin.url)"
  url=${url/git@github.com:/http://github.com/}
  url=${url/.git/}

  # stop script if not a git repo
  if [[ $url == "" ]]; then return; fi

  if [[ $1 =~ "help" ]]; then
    echo "
Bash function to quickly open https://www.github.com in your browser to the relevant URL based on the current git repository and branch.

Available commands are:

  github                      opens GitHub repository and branch
  github compare              opens GitHub branch comparison with \`master\`
  github compare branch_name  opens GitHub branch comparison with \`branch_name\`
  github help                 shows help
  github pr                   opens a GitHub pull request against \`master\`
  github pr branch_name       opens a GitHub pull request against \`branch_name\`
"
    return;
  fi

  # define the possible actions
  if [[ $1 =~ "compare" ]]; then action="compare"
  elif [[ $1 =~ "pr" ]]; then action="pull"
  else action="tree"; fi

  # assign a specific base branch if provided
  if [[ $2 != "" ]]; then base="$2..."
  else base=""; fi

  # build the url to open
  url="${url}/${action}/${base}${branch}"

  echo "Opening ${url} $(\open ${url})"
}
